coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        # basic
        target: 50%
        threshold: 1%
        base: auto
