name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Generate Report
      run: |
        pip install pytest
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
